services:
  db:
    image: postgres:18.0
    container_name: store_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - store_db:/var/lib/postgresql/18/data

volumes:
  store_db: