spring:
# используется для загрузки переменных окружения из внешнего файла .env
# вместо implementation("me.paulschwarz:springboot4-dotenv:$dotenvVersion")
#  config:
#    import: "optional:file:.env[.properties]"
  application:
    name: ${APP_NAME:store-service}

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

#logging:
#  level:
#    liquibase: DEBUG
#    org.hibernate: DEBUG
#    org.springframework.orm.jpa: DEBUG
#    me.paulschwarz.dotenv: DEBUG
#    org.springframework.transaction: DEBUG
